export const image1 = process.env.NEXT_PUBLIC_CLOUDFLARE_ASSETS + '/about-us/CTA/aboutCTA1_vabtpo.webp'
export const image2 = process.env.NEXT_PUBLIC_CLOUDFLARE_ASSETS + '/about-us/CTA/aboutCTA2_iwviig.webp'
export const image3 = process.env.NEXT_PUBLIC_CLOUDFLARE_ASSETS + '/about-us/CTA/aboutCTA3_qlemoz.webp'
export const image4 = process.env.NEXT_PUBLIC_CLOUDFLARE_ASSETS + '/about-us/CTA/aboutCTA4_ahrhj2.webp'
export const image5 = process.env.NEXT_PUBLIC_CLOUDFLARE_ASSETS + '/about-us/CTA/aboutCTA5_rsbabp.webp'
export const image6 = process.env.NEXT_PUBLIC_CLOUDFLARE_ASSETS + '/about-us/CTA/aboutCTA6_sawhww.webp'
