export const image1 = 'https://wtp-assets.oldhat.xyz/about-us/CTA/aboutCTA1_vabtpo.webp'
export const image2 = 'https://wtp-assets.oldhat.xyz/about-us/CTA/aboutCTA2_iwviig.webp'
export const image3 = 'https://wtp-assets.oldhat.xyz/about-us/CTA/aboutCTA3_qlemoz.webp'
export const image4 = 'https://wtp-assets.oldhat.xyz/about-us/CTA/aboutCTA4_ahrhj2.webp'
export const image5 = 'https://wtp-assets.oldhat.xyz/about-us/CTA/aboutCTA5_rsbabp.webp'
export const image6 = 'https://wtp-assets.oldhat.xyz/about-us/CTA/aboutCTA6_sawhww.webp'
